create databse platforma;

create table authors(
  author_id int generated by default as identity primary key,
  author_lastname varchar(32) not null,
  author_firstname varchar(32) not null,
  author_about text
);

insert into authors (author_lastname, author_firstname) values ('Bob', 'John');
insert into authors (author_lastname, author_firstname) values ('Umar', 'Abdullaev');
insert into authors (author_lastname, author_firstname) values ('A''zam', 'Abdusattorov');
insert into authors (author_lastname, author_firstname, author_about) values ('Mirzohid', 'Abdusattorov', 'Lorem ipsum dolor amet');

create table topics (
  topic_id int generated by default as identity primary key,
  author_id int not null references authors(author_id),
  topic_title varchar(64) not null,
  topic_summary text
);

insert into topics (topic_title, author_id) values ('American Gangster', 1);
insert into topics (topic_title, author_id) values ('Charlie: The Life and Art of Charles Chaplin', 2);
insert into topics (topic_title, author_id) values ('Doghouse', 3);
insert into topics (topic_title, author_id) values ('Tess', 4);
insert into topics (topic_title, author_id, topic_summary) values ('Another Gay Movie', 4, 'LOrem ipsum');
insert into topics (topic_title, author_id) values ('Ripley Under Ground', 1);
insert into topics (topic_title, author_id) values ('You''ve Been Trumped', 3);


create table lectures (
  lecture_id int generated by default as identity primary key,
  lecture_title varchar(64) not null,
  lecture_audio varchar(64) not null,
  lecture_summary text,
  lecture_durition varchar,
  lecture_size decimal,
  lecture_islike boolean default false,
  topic_id int not null references topics(topic_id)
);

create table questions (
  question_id int generated by default as identity primary key,
  question_title text not null,
  question_variants json not null,
  lecture_id int not null references lectures(lecture_id)
);

create table users (
  user_id int generated by default as identity primary key,
  user_username varchar(64) not null,
  user_name varchar(32) not null,
  user_password varchar(64),
  user_register_date timestamptz
);

create table users_answers(
  user_answer_id int generated by default as identity primary key,
  question_id int not null references questions(question_id),
  user_id int not null references users(user_id)
);

create table users_heard_lectures (
  user_answer_id int generated by default as identity primary key,
  lecture_id int not null references lectures (lecture_id),
  user_id int not null references users(user_id)
);


