create databse platforma;

create table authors(
  author_id int generated by default as identity primary key,
  author_lastname varchar(32) not null,
  author_firstname varchar(32) not null,
  author_about text
);



create table topics (
  topic_id int generated by default as identity primary key,
  author_id int not null references authors(author_id),
  topic_title varchar(64) not null,
  topic_summary text
);




create table lectures (
  lecture_id int generated by default as identity primary key,
  lecture_title varchar(64) not null,
  lecture_audio varchar(64) not null,
  lecture_summary text,
  lecture_durition varchar,
  lecture_size decimal,
  lecture_islike boolean default false,
  topic_id int not null references topics(topic_id)
);

create table questions (
  question_id int generated by default as identity primary key,
  question_title text not null,
  question_variants json not null,
  lecture_id int not null references lectures(lecture_id)
);

create table users (
  user_id int generated by default as identity primary key,
  user_username varchar(64) not null,
  user_name varchar(32) not null,
  user_password varchar(64),
  user_register_date timestamptz
);

create table users_answers(
  user_answer_id int generated by default as identity primary key,
  question_id int not null references questions(question_id),
  user_id int not null references users(user_id)
);

create table users_heard_lectures (
  user_answer_id int generated by default as identity primary key,
  lecture_id int not null references lectures (lecture_id),
  user_id int not null references users(user_id)
);


